#!/bin/bash

start=$(pwd)
install=false

source ./version

# Parse parameters
while [ $# -ne 0 ]
do
	case "$1" in
		-i)
			install=true
			;;
	esac
	shift
done

(
	cd ..
	ln -s $start/description-pak .

	# Package
	sudo checkinstall $output --maintainer 'Michael Zugaro' --pkgname $name --pkgversion $version --pkgrelease $release --pkglicense GPL --pkggroup Scientific --pkgsource $source --pkgarch $arch --requires $requires --pakdir $start --delspec

	rm description-pak
)

# Install?
if $install
then
	sudo eval $install_cmd
fi
