#!/bin/bash

source ./version

(
	echo "***********************************************************************************"
	echo "  Cleaning (removing object files and executables)"
	echo "***********************************************************************************"
	cd ..
	make clean

	echo "***********************************************************************************"
	echo "  Archiving"
	echo "***********************************************************************************"

	dir=$(basename $(pwd))
	cd ..
	sudo tar -cvz --exclude $dir/$tarball -f $dir/package/$tarball $dir
)
