process_nlxconvert: OutputFile Class Reference
OutputFile Class Reference
#include <outputfile.h>
Public Member Functions
OutputFile ()
OutputFile (string filename, bool force, ios_base::openmode mode)
virtual ~OutputFile ()
virtual void set (string filename, bool force, ios_base::openmode mode)
virtual void create () throw (NLXError)
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
OutputFile::OutputFile () [inline]
Constructor
OutputFile::OutputFile (string filename, bool force, ios_base::openmode mode) [inline]
Constructor
Parameters:
filename output file name
force overwrite existing file?
mode text vs binary
virtual OutputFile::~OutputFile () [inline, virtual]
Destructor
Member Function Documentation
virtual void OutputFile::set (string filename, bool force, ios_base::openmode mode) [inline, virtual]
Setter
Parameters:
filename output file name
force overwrite existing file?
mode text vs binary
void OutputFile::create () throw (NLXError) [virtual]
Create output file
Referenced by NLXExtractor::extractEvents(), NLXExtractor::extractSpots(), NLXExtractor::extractWideband(), NLXExtractor::findRestarts(), and NLXExtractor::syncSpots().
The documentation for this class was generated from the following files:
outputfile.h
outputfile.cpp