process_nlxconvert: SMIFileCollection Class Reference
SMIFileCollection Class Reference
#include <smifilecollection.h>
Public Member Functions
SMIFileCollection (Time frameDuration)
SMIFileCollection ()
virtual ~SMIFileCollection ()
virtual void set (Time frameDuration)
virtual void add (string filename)
virtual void open () throw (NLXError)
virtual void close ()
virtual void init () throw (NLXError)
virtual long getNFrames ()
virtual bool readFrame ()
virtual Time getTimestamp ()
virtual Time getGap ()
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
SMIFileCollection::SMIFileCollection (Time frameDuration) [inline]
Constructor
Parameters:
frameDuration frame duration in µs
SMIFileCollection::SMIFileCollection () [inline]
Constructor
virtual SMIFileCollection::~SMIFileCollection () [inline, virtual]
Destructor
Member Function Documentation
virtual void SMIFileCollection::set (Time frameDuration) [inline, virtual]
Setter
Parameters:
frameDuration frame duration in µs
Referenced by NLXExtractor::NLXExtractor().
void SMIFileCollection::add (string filename) [virtual]
Add an input file to the collection
Parameters:
filename name of the file to add
Add an input file to the collection
References SMIFile::set().
void SMIFileCollection::open () throw (NLXError) [virtual]
Open files
Returns:
false if one of the files could not be opened
Open files
void SMIFileCollection::close () [virtual]
Close files
Close files
void SMIFileCollection::init () throw (NLXError) [virtual]
Determine total number of records
Read frequency and record duration, and determine number of records
long SMIFileCollection::getNFrames () [virtual]
Count the total number of frames in the files
Returns:
number of frames
Count the total number of records in the files
Referenced by NLXExtractor::syncSpots().
bool SMIFileCollection::readFrame () [virtual]
Read next frame
Returns:
false if the frame could not be read (end of last file)
Read next frame
References SMIFile::t.
Referenced by NLXExtractor::syncSpots().
virtual Time SMIFileCollection::getTimestamp () [inline, virtual]
Get current timestamp
Returns:
current timestamp
Referenced by NLXExtractor::syncSpots().
virtual Time SMIFileCollection::getGap () [inline, virtual]
Get current gap
Returns:
current gap in µs
Referenced by NLXExtractor::syncSpots().
The documentation for this class was generated from the following files:
smifilecollection.h
smifilecollection.cpp