#!/bin/bash

#////////////////////////////////////////////////////////////////////////////
#//
#//   Convert from .smr (CED files) to wideband data format .dat
#//
#//   copyright       (C) 2007-2010 by Michaël Zugaro
#//   email           michael.zugaro@college-de-france.fr
#//
#//   This program is free software; you can redistribute it and/or modify
#//   it under the terms of the GNU General Public License as published by
#//   the Free Software Foundation; either version 3 of the License, or
#//   (at your option) any later version.
#//
#////////////////////////////////////////////////////////////////////////////

# Source helper functions
source ndm_functions

# Parse command-line
program=$(basename $0)
if [ $# -ne 1 ]
then
	echo_error "usage: $program xml-file"
	exit $GENERAL_ERROR
fi
session=${1%.xml}
directory=$(basename "$(pwd)")

# Print a header to indicate current processing step
print_header "$session - Converting SMR files -> dat"

# Check required programs
check_commands_installed xpathReader process_smrconvert

# Check input files
inputs_missing $session.xml && exit $INPUTS_MISSING

# ////////////////////////////////////////////////////////////////////////////////////////////////
# // Read Parameters
# ////////////////////////////////////////////////////////////////////////////////////////////////

opts="-d"

suffixes=($(read_script_parameter $session suffixes))
reverse=$(read_script_parameter $session reverse)
excluded=($(read_script_parameter $session channelsExcluded excluded))

check_mandatory_variable ${suffixes[0]} "missing suffixes"
check_mandatory_variable $reverse "should signals be reversed?"

$reverse && opts="$opts -r"

# ////////////////////////////////////////////////////////////////////////////////////////////////
# // Process
# ////////////////////////////////////////////////////////////////////////////////////////////////

outputs_exist=false
# Convert selected files
n=$(get_n_suffixes ${suffixes[*]})
for (( i=0;i<$n;i++ ))
do
	suffix=$(get_suffix $i ${suffixes[*]})
	echo_info "Converting '$session-$suffix.smr'"
	if outputs_exist $session-$suffix.dat
	then
		outputs_exist=true
		continue
	fi
	smr_file=../$directory-$suffix/$session-$suffix.smr
	inputs_missing  && exit $INPUTS_MISSING
	options="$opts"
	if [ ! -z "${excluded[$i]}" ] && [ "${excluded[$i]}" != '-' ]
	then
		options="$options -x ${excluded[$i]}"
		echo_info "excluding channels ${excluded[$i]}"
	fi
	process_smrconvert $options $smr_file
	check_command_status process_smrconvert
done

if $outputs_exist
then
	exit $OUTPUTS_EXIST
fi
