#!/bin/bash

#////////////////////////////////////////////////////////////////////////////
#//
#//   Extract timestamps from .smi files (Neuralynx systems)
#//
#//   copyright       (C) 2009-2011 by Michaël Zugaro
#//   email           michael.zugaro@college-de-france.fr
#//
#//   This program is free software; you can redistribute it and/or modify
#//   it under the terms of the GNU General Public License as published by
#//   the Free Software Foundation; either version 3 of the License, or
#//   (at your option) any later version.
#//
#////////////////////////////////////////////////////////////////////////////

# Source helper functions
source ndm_functions

# Parse command-line
program=$(basename $0)
if [ $# -ne 1 ]
then
	echo_error "usage: $program xml-file"
	exit $GENERAL_ERROR
fi
session=${1%.xml}
directory=$(basename "$(pwd)")

# Print a header to indicate current processing step
print_header "$session - Converting SMI files -> sts"

# Check required programs
check_commands_installed xpathReader process_nlxconvert

# Check input/output files
inputs_missing $session.xml && exit $INPUTS_MISSING

# ////////////////////////////////////////////////////////////////////////////////////////////////
# // Read Parameters
# ////////////////////////////////////////////////////////////////////////////////////////////////

options="-v"

suffix=$(read_script_parameter $session suffix)
gap=$(read_script_parameter $session gap)

check_mandatory_variable $suffix "missing suffix"
if check_optional_variable $gap
then
	options="$options -g $gap"
fi

# ////////////////////////////////////////////////////////////////////////////////////////////////
# // Process
# ////////////////////////////////////////////////////////////////////////////////////////////////

# Make sure output file does not already exist
outputs_exist $session.sts && exit $OUTPUTS_EXIST
# Is there a .restart file available (or a .nev) to help us find acquisition restart events?
restart_file=$(ls $session-$suffix.restart 2>/dev/null)
nev_file=""
if [ -z "$restart_file" ]
then
	nev_file=$(ls ../$directory-$suffix/$session-$suffix.nev 2>/dev/null)
	# Create the .restart file if it does not exist
	if [ -z "$nev_file" ]
	then
		echo_warning "missing .nev and .restart files, will try to guess 'restart acquisition' events."
	else
		options="$options -a"
	fi
fi
# Is there a sync file available (or .ncs files) to synchronize events?
sync_file=$(ls $session-$suffix.sync 2>/dev/null)
ncs_files=""
if [ -z "$sync_file" ]
then
	ncs_files=$(ls ../$directory-$suffix/$session-$suffix*ncs 2>/dev/null)
	# Create the .sync file if it does not exist
	if [ -z "$ncs_files" ]
	then
		echo_warning "missing .ncs and .sync files, video cannot be synchronized with wideband signals."
	else
		options="$options -s"
	fi
fi
# Convert smi file
smi_files=$(ls ../$directory-$suffix/$session-$suffix*.smi 2>/dev/null)
[ -z "$smi_files" ] && echo_warning "no .smi files found" && continue
process_nlxconvert $options -o $session $smi_files $nev_file $restart_file $ncs_files $sync_file
check_command_status process_nlxconvert
