#!/bin/bash

#////////////////////////////////////////////////////////////////////////////
#//
#//   Rename events and event files
#//
#//   copyright       (C) 2007-2010 by Michaël Zugaro
#//   email           michael.zugaro@college-de-france.fr
#//
#//   This program is free software; you can redistribute it and/or modify
#//   it under the terms of the GNU General Public License as published by
#//   the Free Software Foundation; either version 3 of the License, or
#//   (at your option) any later version.
#//
#////////////////////////////////////////////////////////////////////////////

# Source helper functions
source ndm_functions

# Parse command-line
program=$(basename $0)
if [ $# -ne 1 ]
then
	echo_error "usage: $program xml-file"
	exit $GENERAL_ERROR
fi
session=${1%.xml}

# Transform arcane codes into human-readable event messages
[ -z "$(ls $session*evt 2> /dev/null)" ] && exit $NO_ERROR
for eventfile in $session*evt
do
	sed -i \
		-e 's/[[:space:]]0$/\tStimulation/' \
		-e 's/[[:space:]]1$/\tRipple Left/' \
		-e 's/[[:space:]]2$/\tRipple Right/' \
		-e 's/[[:space:]]3$/\tDisable Stim/' \
		-e 's/[[:space:]]4$/\tEnable Stim/' \
		-e 's/[[:space:]]66$/\tBlock Stim/' \
		-e 's/[[:space:]]82$/\tUnblock Stim/' \
		$eventfile
done

# Rename event files
rename -f 's/e30/bck/;s/e31/kil/;s/e35/stm/;s/-red//' $session*evt
