process_nlxconvert: NVTFile Class Reference
NVTFile Class Reference
#include <nvtfile.h>
Public Member Functions
NVTFile (string filename, Time frameDuration)
NVTFile ()
virtual ~NVTFile ()
virtual void set (string filename, Time frameDuration)
virtual void open () throw (NLXError)
virtual void init ()
virtual bool readFrame ()
virtual void writeFrame (ofstream &output)
virtual void writeLastFrame (ofstream &output)
virtual long getNFrames ()
virtual Time getGap ()
virtual Time getTimestamp ()
virtual void showFileHeader ()
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
NVTFile::NVTFile (string filename, Time frameDuration) [inline]
Constructor
Parameters:
filename input file name
frameDuration frame duration in µs
NVTFile::NVTFile () [inline]
Constructor
virtual NVTFile::~NVTFile () [inline, virtual]
Destructor
Member Function Documentation
virtual void NVTFile::set (string filename, Time frameDuration) [inline, virtual]
Setter
Parameters:
filename input file name
frameDuration theoretical frame duration
void NVTFile::open () throw (NLXError) [virtual]
Open file
Returns:
false if the file could not be opened
Open file
void NVTFile::init () [virtual]
Read frequency and frame duration, and determine number of frames
Read frequency and frame duration, and determine number of frames
bool NVTFile::readFrame () [virtual]
Read next frame
Returns:
false if the frame could not be read (end of file)
Read next frame
Referenced by NLXExtractor::extractSpots().
void NVTFile::writeFrame (ofstream & output) [virtual]
Write frame data to output file
Write frame data to output file
Referenced by NLXExtractor::extractSpots().
void NVTFile::writeLastFrame (ofstream & output) [virtual]
Write last frame (dummy data) to output file (so that we know how many frames were in the video, even if there is no spot in the last frame!)
Write last frame (dummy data) to output file (so that we know how many frames were in the video, even if there is no spot in the last frame!)
Referenced by NLXExtractor::extractSpots().
virtual long NVTFile::getNFrames () [inline, virtual]
Count the number of frames in the file
Returns:
number of frames
Referenced by NLXExtractor::extractSpots().
virtual Time NVTFile::getGap () [inline, virtual]
Get current gap
Returns:
current gap in µs
Referenced by NLXExtractor::extractSpots().
virtual Time NVTFile::getTimestamp () [inline, virtual]
Get current timestamp
Returns:
current timestamp
Referenced by NLXExtractor::extractSpots().
void NVTFile::showFileHeader () [virtual]
Show file header
Show file header
Referenced by NLXExtractor::showFileHeaders().
The documentation for this class was generated from the following files:
nvtfile.h
nvtfile.cpp