process_nlxconvert: NEVFile Class Reference
NEVFile Class Reference
#include <nevfile.h>
Public Member Functions
NEVFile (string filename)
NEVFile ()
virtual ~NEVFile ()
virtual void set (string filename)
virtual void open () throw (NLXError)
virtual void init ()
virtual bool readRecord ()
virtual bool restarted ()
virtual void writeRecord (ofstream &output)
virtual void setShift (Time s)
virtual void addToShift (Time s)
virtual long getNRecords ()
virtual Time getTimestamp ()
virtual Time getGap ()
virtual void showFileHeader ()
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
NEVFile::NEVFile (string filename) [inline]
Constructor
Parameters:
filename input file name
NEVFile::NEVFile () [inline]
Constructor
virtual NEVFile::~NEVFile () [inline, virtual]
Destructor
Member Function Documentation
virtual void NEVFile::set (string filename) [inline, virtual]
Setter
Parameters:
filename input file name
void NEVFile::open () throw (NLXError) [virtual]
Open file
Returns:
false if the file could not be opened
Open file
void NEVFile::init () [virtual]
Read frequency and record duration, and determine number of records
Read frequency and record duration, and determine number of records
Referenced by NLXExtractor::findRestarts().
bool NEVFile::readRecord () [virtual]
Read next data record
Returns:
false if the record could not be read (end of file)
Read next record
Referenced by NLXExtractor::extractEvents(), and NLXExtractor::findRestarts().
bool NEVFile::restarted () [virtual]
Test whether acquisition was restarted
Test whether acquisition was restarted
Referenced by NLXExtractor::extractEvents(), and NLXExtractor::findRestarts().
void NEVFile::writeRecord (ofstream & output) [virtual]
Write record data to output file
Write record data to output file
Referenced by NLXExtractor::extractEvents().
void NEVFile::setShift (Time s) [virtual]
Set initial shift from 0, to synchronize with wideband signals
Set initial shift from 0, to synchronize with wideband signals
Referenced by NLXExtractor::extractEvents().
void NEVFile::addToShift (Time s) [virtual]
Add shift, to synchronize with wideband signals
Add shift, to synchronize with wideband signals
Referenced by NLXExtractor::extractEvents().
virtual long NEVFile::getNRecords () [inline, virtual]
Count the number of records in the file
Returns:
number of records
Referenced by NLXExtractor::extractEvents(), and NLXExtractor::findRestarts().
virtual Time NEVFile::getTimestamp () [inline, virtual]
Get current timestamp
Returns:
current timestamp
Referenced by NLXExtractor::extractEvents(), and NLXExtractor::findRestarts().
virtual Time NEVFile::getGap () [inline, virtual]
Get time gap between current and previous events
Returns:
time gap
void NEVFile::showFileHeader () [virtual]
Show file header
Show file header
Referenced by NLXExtractor::showFileHeaders().
The documentation for this class was generated from the following files:
nevfile.h
nevfile.cpp