process_nlxconvert: NLXExtractor Class Reference
NLXExtractor Class Reference
#include <nlxextractor.h>
Public Member Functions
NLXExtractor (bool info, bool wideband, bool spots, bool events, bool timestamps, bool sync, bool restart, bool force, bool reverse, Time threshold, Time frameDuration)
virtual ~NLXExtractor ()
virtual void init (char *inputs[], int nInputs, char *output) throw (NLXError)
virtual void extractWideband () throw (NLXError)
virtual void readSyncs (string filename) throw (NLXError)
virtual void findSyncs ()
virtual void extractSpots () throw (NLXError)
virtual void syncSpots () throw (NLXError)
virtual void extractEvents () throw (NLXError)
virtual void readRestarts (string filename) throw (NLXError)
virtual void findRestarts ()
virtual bool isRestart (Time gap, Time timestamp)
virtual void extract () throw (NLXError)
virtual void showFileHeaders ()
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
NLXExtractor::NLXExtractor (bool info, bool wideband, bool spots, bool events, bool timestamps, bool sync, bool restart, bool force, bool reverse, Time threshold, Time frameDuration) [inline]
Constructor
Parameters:
info show file headers?
wideband convert wideband signals?
spots convert tracking data?
events convert events?
timestamps generate timestamp files?
sync generate sync file?
restart generate restart file?
force force overwrite?
reverse should wideband signals be reversed?
threshold max time gap between successive records
frameDuration approx. duration of a video frame
References SMIFileCollection::set().
virtual NLXExtractor::~NLXExtractor () [inline, virtual]
Destructor
References NCSFileCollection::close().
Member Function Documentation
void NLXExtractor::init (char * inputs[], int nInputs, char * output) throw (NLXError) [virtual]
Initialization
Parameters:
inputs input file names
nInputs number of input files
output output file base name
Initialization
void NLXExtractor::extractWideband () throw (NLXError) [virtual]
Extract to .dat
Extract to .dat
References OutputFile::create(), NCSFileCollection::fillMissingRecords(), NCSFileCollection::getGap(), NCSFileCollection::getNRecords(), NCSFileCollection::getRecordDuration(), NCSFileCollection::getTimestamp(), isRestart(), NCSFileCollection::readRecord(), NLXError::report(), NCSFileCollection::skipMissingRecords(), and NCSFileCollection::writeRecord().
Referenced by extract().
void NLXExtractor::readSyncs (string filename) throw (NLXError) [virtual]
Read sync info from file
Read sync info from file
void NLXExtractor::findSyncs () [virtual]
Browse .ncs files to find sync info
Browse .ncs files to find sync info
References NCSFileCollection::getGap(), NCSFileCollection::getNRecords(), NCSFileCollection::getTimestamp(), isRestart(), NCSFileCollection::readRecord(), and NCSFileCollection::skipMissingRecords().
Referenced by extract().
void NLXExtractor::extractSpots () throw (NLXError) [virtual]
Extract to .spots
Extract to .spots
throw NLXError(NLXError::READ_ERROR,"negative gap between successive frames.");
References OutputFile::create(), NVTFile::getGap(), NVTFile::getNFrames(), NVTFile::getTimestamp(), isRestart(), NVTFile::readFrame(), NLXError::report(), NVTFile::writeFrame(), and NVTFile::writeLastFrame().
Referenced by extract().
void NLXExtractor::syncSpots () throw (NLXError) [virtual]
Resynchronize .spots file (using .smi file)
Resynchronize .spots file (using .smi file)
throw NLXError(NLXError::READ_ERROR,"negative gap between successive frames.");
References OutputFile::create(), SMIFileCollection::getGap(), SMIFileCollection::getNFrames(), SMIFileCollection::getTimestamp(), isRestart(), SMIFileCollection::readFrame(), and NLXError::report().
Referenced by extract().
void NLXExtractor::extractEvents () throw (NLXError) [virtual]
Extract to .evt
Extract to .evt
References NEVFile::addToShift(), OutputFile::create(), NEVFile::getNRecords(), NEVFile::getTimestamp(), NEVFile::readRecord(), NLXError::report(), NEVFile::restarted(), NEVFile::setShift(), and NEVFile::writeRecord().
Referenced by extract().
void NLXExtractor::readRestarts (string filename) throw (NLXError) [virtual]
Read 'restart acquisition' events from file
Read 'restart acquisition' events from file
void NLXExtractor::findRestarts () [virtual]
Find 'restart acquisition' events
Find 'restart acquisition' events
References OutputFile::create(), NEVFile::getNRecords(), NEVFile::getTimestamp(), NEVFile::init(), NEVFile::readRecord(), NLXError::report(), and NEVFile::restarted().
Referenced by extract().
bool NLXExtractor::isRestart (Time gap, Time timestamp) [virtual]
Does a given timestamp correspond to a restart?
Does a given timestamp correspond to a restart?
Referenced by extractSpots(), extractWideband(), findSyncs(), and syncSpots().
void NLXExtractor::extract () throw (NLXError) [virtual]
Extract
Extract
References extractEvents(), extractSpots(), extractWideband(), findRestarts(), findSyncs(), NLXError::report(), and syncSpots().
void NLXExtractor::showFileHeaders () [virtual]
Show file headers
Show file headers
References NEVFile::showFileHeader(), NVTFile::showFileHeader(), and NCSFileCollection::showFileHeaders().
The documentation for this class was generated from the following files:
nlxextractor.h
nlxextractor.cpp