process_nlxconvert: NLXError Class Reference
NLXError Class Reference
#include <nlxerror.h>
Public Types
enum ErrorType { READ_ERROR, WRITE_ERROR }
Public Member Functions
NLXError (ErrorType type, string message)
virtual ~NLXError () throw ()
virtual string report () const
virtual ErrorType getType () const
Detailed Description
Author:
Michael Zugaro
Member Enumeration Documentation
enum NLXError::ErrorType
Error types
Constructor & Destructor Documentation
NLXError::NLXError (ErrorType type, string message)
Constructor
Parameters:
type type of error
message error message
NLXError::~NLXError () throw () [virtual]
Destructor
Member Function Documentation
string NLXError::report () const [virtual]
Report error
Returns:
error message
Referenced by NLXExtractor::extract(), NLXExtractor::extractEvents(), NLXExtractor::extractSpots(), NLXExtractor::extractWideband(), NLXExtractor::findRestarts(), and NLXExtractor::syncSpots().
NLXError::ErrorType NLXError::getType () const [virtual]
Get error type
Returns:
error type
The documentation for this class was generated from the following files:
nlxerror.h
nlxerror.cpp