process_nlxconvert: NCSFileCollection Class Reference
NCSFileCollection Class Reference
#include <ncsfilecollection.h>
Public Member Functions
NCSFileCollection (bool reverse=false)
virtual ~NCSFileCollection ()
virtual void set (bool reverse)
virtual void add (string filename)
virtual void open () throw (NLXError)
virtual void close ()
virtual void init () throw (NLXError)
virtual long getNRecords ()
virtual bool readRecord ()
virtual void skipMissingRecords ()
virtual void fillMissingRecords (ofstream &output)
virtual void writeRecord (ofstream &output)
virtual void showFileHeaders ()
virtual Time getTimestamp ()
virtual Time getRecordDuration ()
virtual Time getGap ()
virtual Frequency getFrequency ()
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
NCSFileCollection::NCSFileCollection (bool reverse = false) [inline]
Constructor
virtual NCSFileCollection::~NCSFileCollection () [inline, virtual]
Destructor
Member Function Documentation
virtual void NCSFileCollection::set (bool reverse) [inline, virtual]
Setter
Parameters:
reverse true if signals should be reversed
void NCSFileCollection::add (string filename) [virtual]
Add an input file to the collection
Parameters:
filename name of the file to add
Add an input file to the collection
References NCSFile::set().
void NCSFileCollection::open () throw (NLXError) [virtual]
Open files
Returns:
false if one of the files could not be opened
Open files
void NCSFileCollection::close () [virtual]
Close files
Close files
Referenced by NLXExtractor::~NLXExtractor().
void NCSFileCollection::init () throw (NLXError) [virtual]
Read frequency and record duration, and determine number of records
Read frequency and record duration, and determine number of records
References NCSFile::frequency, and NCSFile::recordDuration.
long NCSFileCollection::getNRecords () [virtual]
Count the number of records in the files
Returns:
number of records
Count the maximum number of records in the files
References NCSFile::nRecords.
Referenced by NLXExtractor::extractWideband(), and NLXExtractor::findSyncs().
bool NCSFileCollection::readRecord () [virtual]
Read next data record
Returns:
false if the record could not be read (end of file)
Read next record
References NCSFile::gap, and NCSFile::t.
Referenced by NLXExtractor::extractWideband(), and NLXExtractor::findSyncs().
void NCSFileCollection::skipMissingRecords () [virtual]
Skip missing records
Skip missing records
Referenced by NLXExtractor::extractWideband(), and NLXExtractor::findSyncs().
void NCSFileCollection::fillMissingRecords (ofstream & output) [virtual]
Fill missing records
Fill missing records
Referenced by NLXExtractor::extractWideband().
void NCSFileCollection::writeRecord (ofstream & output) [virtual]
Write record data to output file
Write record data to output file
References NCSFile::recordData.
Referenced by NLXExtractor::extractWideband().
void NCSFileCollection::showFileHeaders () [virtual]
Show file headers
Show file headers
References NCSFile::fileHeader, and NCSFile::filename.
Referenced by NLXExtractor::showFileHeaders().
virtual Time NCSFileCollection::getTimestamp () [inline, virtual]
Get current timestamp
Returns:
current timestamp
Referenced by NLXExtractor::extractWideband(), and NLXExtractor::findSyncs().
virtual Time NCSFileCollection::getRecordDuration () [inline, virtual]
Get record duration
Returns:
current record duration µs
Referenced by NLXExtractor::extractWideband().
virtual Time NCSFileCollection::getGap () [inline, virtual]
Get current gap
Returns:
current gap in µs
Referenced by NLXExtractor::extractWideband(), and NLXExtractor::findSyncs().
virtual Frequency NCSFileCollection::getFrequency () [inline, virtual]
Get (common) sampling frequency
Returns:
frequency
References NCSFile::frequency.
The documentation for this class was generated from the following files:
ncsfilecollection.h
ncsfilecollection.cpp