process_smrconvert: SONExtractor Class Reference
SONExtractor Class Reference
#include <sonextractor.h>
Public Member Functions
SONExtractor (SONFile *file, bool header, bool dat, bool spk, bool evt, bool force, bool reverse, uint16_t nChannelsListed=0, uint16_t channelList[]=NULL, bool include=true)
virtual ~SONExtractor ()
virtual void checkDat () throw (SONError)
virtual void checkSpk () throw (SONError)
virtual void checkEvt () throw (SONError)
virtual void extractDat () throw (SONError)
virtual void extractSpk () throw (SONError)
virtual void extractEvt () throw (SONError)
virtual void extract () throw (SONError)
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
SONExtractor::SONExtractor (SONFile * file, bool header, bool dat, bool spk, bool evt, bool force, bool reverse, uint16_t nChannelsListed = 0, uint16_t channelList[] = NULL, bool include = true)
Constructor
Parameters:
file session file
header convert header?
dat convert to dat?
spk convert to spk/res?
evt convert to evt?
force force overwrite?
reverse reverse wideband data?
nChannelsListed number of ADC channels to extract or exclude
channelList list of ADC channels to extract or exclude
include include (true) or exclude (false) listed channels
References SONFile::getName().
SONExtractor::~SONExtractor () [virtual]
Destructor
Member Function Documentation
void SONExtractor::checkDat () throw (SONError) [virtual]
Make sure .dat output file do not exist (unless forcing overwrite)
Referenced by extract().
void SONExtractor::checkSpk () throw (SONError) [virtual]
Make sure .spk/.res output files do not exist (unless forcing overwrite)
Referenced by extract().
void SONExtractor::checkEvt () throw (SONError) [virtual]
Make sure .evt output file do not exist (unless forcing overwrite)
Referenced by extract().
void SONExtractor::extractDat () throw (SONError) [virtual]
Extract to dat
References SONADCChannels::done(), SONADCChannels::percentDone(), SONADCChannels::read(), and SONADCChannels::write().
Referenced by extract().
void SONExtractor::extractSpk () throw (SONError) [virtual]
Extract to spk/res
References SONADCMarkChannel::read(), and SONADCMarkChannel::write().
Referenced by extract().
void SONExtractor::extractEvt () throw (SONError) [virtual]
Extract to evt
References SONError::getType(), SONEventChannel::read(), and SONEventChannel::write().
Referenced by extract().
void SONExtractor::extract () throw (SONError) [virtual]
Extract
References checkDat(), checkEvt(), checkSpk(), extractDat(), extractEvt(), extractSpk(), SONFile::getChannelInfo(), SONFile::getFileHeader(), SONFile::getNChannels(), SONFile::getSamplingFrequency(), SONFile::init(), SONFile::isADCChannel(), SONFile::isADCMarkChannel(), SONFile::isEventChannel(), and SONFile::open().
The documentation for this class was generated from the following files:
sonextractor.h
sonextractor.cpp