process_smrconvert: SONChannelInfo Class Reference
SONChannelInfo Class Reference
#include <sonchannelinfo.h>
Public Types
enum {
Off = 0, ADC, EventFall, EventRise,
EventBoth, Marker, ADCMark, RealMark,
TextMark, RealWave
}
Public Member Functions
SONChannelInfo ()
SONChannelInfo (SONFile *file, uint16_t channel)
virtual ~SONChannelInfo ()
virtual void init (SONFile *file, uint16_t channel)
virtual void read ()
virtual bool isEmpty () const
virtual uint32_t getNBlocks () const
virtual int64_t getFirstBlockOffset () const
virtual uint16_t getNSamplesPerWaveform () const
virtual int32_t getLChanDvd () const
virtual float getRate () const
virtual uint16_t getDivide () const
virtual bool isADCChannel () const
virtual bool isADCMarkChannel () const
virtual bool isEventChannel () const
virtual bool isSimpleEventChannel () const
virtual bool isMarkerChannel () const
virtual bool isTextMarkChannel () const
Static Public Attributes
static const int fileHeaderSize = 512
static const int channelHeaderSize = 140
static const int diskBlock = 512
Friends
class SONExtractor
ostream & operator<< (ostream &out, const SONChannelInfo &channelInfo)
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
SONChannelInfo::SONChannelInfo ()
Default constructor (necessary to create arrays of SONChannelInfo)
See also:
init
SONChannelInfo::SONChannelInfo (SONFile * file, uint16_t channel)
Constructor
Parameters:
file input file
channel channel number
SONChannelInfo::~SONChannelInfo () [virtual]
Destructor
Member Function Documentation
void SONChannelInfo::init (SONFile * file, uint16_t channel) [inline, virtual]
Initialization (necessary to create arrays of SONChannelInfo)
Parameters:
file input file
channel channel number
Referenced by SONFile::init().
void SONChannelInfo::read () [virtual]
Read SON file header
References channelHeaderSize, diskBlock, fileHeaderSize, and SONFile::getVersion().
Referenced by SONFile::init().
bool SONChannelInfo::isEmpty () const [inline, virtual]
Test whether the channel is empty
uint32_t SONChannelInfo::getNBlocks () const [inline, virtual]
Get number of blocks in the channel
Returns:
number of blocks
Referenced by SONFile::getNBlocks().
int64_t SONChannelInfo::getFirstBlockOffset () const [inline, virtual]
Get file offset of first block of data for the channel
Returns:
first block
Referenced by SONFile::getFirstBlockOffset().
uint16_t SONChannelInfo::getNSamplesPerWaveform () const [inline, virtual]
Get number of samples per waveform
Returns:
number of samples per waveform
Referenced by SONFile::getNSamplesPerWaveform().
int32_t SONChannelInfo::getLChanDvd () const [inline, virtual]
Get lChanDvd field (used to compute timestamps)
Returns:
lChanDvd
Referenced by SONFile::getTicksPerSI().
float SONChannelInfo::getRate () const [inline, virtual]
Get sampling rate
Returns:
sampling rate
uint16_t SONChannelInfo::getDivide () const [inline, virtual]
Get divide
Returns:
divide
Referenced by SONFile::getTicksPerSI().
bool SONChannelInfo::isADCChannel () const [inline, virtual]
Is this an ADC channel?
Returns:
true if this is an ADC channel
Referenced by SONFile::isADCChannel().
bool SONChannelInfo::isADCMarkChannel () const [inline, virtual]
Is this an ADC mark channel?
Returns:
true if this is an ADC mark channel
Referenced by SONFile::isADCMarkChannel().
bool SONChannelInfo::isEventChannel () const [inline, virtual]
Is this an event channel (EventRise, EventFall, EventBoth, Marker, RealMark or TextMark)?
Returns:
true if this is an event channel
Referenced by SONFile::isEventChannel().
bool SONChannelInfo::isSimpleEventChannel () const [inline, virtual]
Is this a simple Event channel (EventRise, EventFall or EventBoth)?
Returns:
true if this is a simple Event channel
Referenced by SONFile::isSimpleEventChannel().
bool SONChannelInfo::isMarkerChannel () const [inline, virtual]
Is this an Marker channel?
Returns:
true if this is an Marker channel
Referenced by SONFile::isMarkerChannel().
bool SONChannelInfo::isTextMarkChannel () const [inline, virtual]
Is this an TextMark channel?
Returns:
true if this is an TextMark channel
Referenced by SONFile::isTextMarkChannel().
Member Data Documentation
const int SONChannelInfo::fileHeaderSize = 512 [static]
File header size (in bytes)
Referenced by read().
const int SONChannelInfo::channelHeaderSize = 140 [static]
Channel header size (in bytes)
Referenced by read().
const int SONChannelInfo::diskBlock = 512 [static]
file offset coeff (file format version >= 9)
Referenced by read().
The documentation for this class was generated from the following files:
sonchannelinfo.h
sonchannelinfo.cpp