process_smrconvert: SONFile Class Reference
SONFile Class Reference
#include <sonfile.h>
Public Member Functions
SONFile (string filename)
virtual ~SONFile ()
virtual void open () throw (SONError)
virtual void init () throw (SONError)
virtual void readBlockHeaders (uint16_t channel)
virtual string getName () const
virtual uint16_t getNChannels () const
virtual const int16_t getVersion () const
virtual const SONFileHeader * getFileHeader () const
virtual const SONChannelInfo * getChannelInfo (uint16_t channel) const
virtual const SONBlockHeaders * getBlockHeaders (uint16_t channel) const
virtual double getSamplingFrequency (uint16_t channel) const
virtual double getSecondsPerTick () const
virtual uint16_t getTicksPerSI (uint16_t channel) const
virtual uint32_t getNBlocks (uint16_t channel) const
virtual uint16_t getNSamplesInBlock (uint16_t channel, uint32_t block) const
virtual int64_t getNSamples (uint16_t channel) const
virtual uint16_t getNSamplesPerWaveform (uint16_t channel) const
virtual int64_t getFirstBlockOffset (uint16_t channel) const
virtual int64_t getBlockOffset (uint16_t channel, uint32_t block) const
virtual bool isADCChannel (uint16_t channel) const
virtual bool isADCMarkChannel (uint16_t channel) const
virtual bool isEventChannel (uint16_t channel) const
virtual bool isSimpleEventChannel (uint16_t channel) const
virtual bool isMarkerChannel (uint16_t channel) const
virtual bool isTextMarkChannel (uint16_t channel) const
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
SONFile::SONFile (string filename)
Constructor
Parameters:
filename smr file name
SONFile::~SONFile () [virtual]
Destructor
Member Function Documentation
void SONFile::open () throw (SONError) [virtual]
Open file
Referenced by SONExtractor::extract().
void SONFile::init () throw (SONError) [virtual]
Initialization: read file header and channel information
References SONFileHeader::getNChannels(), SONChannelInfo::init(), SONChannelInfo::read(), and SONFileHeader::read().
Referenced by SONExtractor::extract().
void SONFile::readBlockHeaders (uint16_t channel) [inline, virtual]
Read block headers for a given channel. This is not done on initialization because it can take a lot of time and we do not want to block the program unless this is absolutely necessary.
References SONBlockHeaders::read().
Referenced by SONEventChannel::read(), SONADCMarkChannel::read(), and SONADCChannels::read().
string SONFile::getName () const [inline, virtual]
Get file name
Returns:
file name
Referenced by SONExtractor::SONExtractor().
uint16_t SONFile::getNChannels () const [inline, virtual]
Get number of channels
Returns:
number of channels
References SONFileHeader::getNChannels().
Referenced by SONExtractor::extract().
const int16_t SONFile::getVersion () const [inline, virtual]
Get file format version
Returns:
file format version
References SONFileHeader::getSystemID().
Referenced by SONChannelInfo::read(), and SONBlockHeaders::readNext().
const SONFileHeader * SONFile::getFileHeader () const [inline, virtual]
Get file header
Returns:
file header
Referenced by SONExtractor::extract().
const SONChannelInfo * SONFile::getChannelInfo (uint16_t channel) const [inline, virtual]
Get channel information
Parameters:
channel channel ID
Returns:
channel info
Referenced by SONExtractor::extract().
const SONBlockHeaders * SONFile::getBlockHeaders (uint16_t channel) const [inline, virtual]
Get block headers for a given channel
Parameters:
channel channel ID
Returns:
block headers
double SONFile::getSamplingFrequency (uint16_t channel) const [inline, virtual]
Get sampling frequency (in Hz) for a given channel
Parameters:
channel channel ID
Returns:
sampling frequency
References getSecondsPerTick(), and getTicksPerSI().
Referenced by SONExtractor::extract().
double SONFile::getSecondsPerTick () const [inline, virtual]
Get clock tick duration (in s)
Returns:
clock tick duration
References SONFileHeader::getSecondsPerTick().
Referenced by getSamplingFrequency(), and SONEventChannel::write().
uint16_t SONFile::getTicksPerSI (uint16_t channel) const [inline, virtual]
Get sampling interval (in ticks) for a given channel
Parameters:
channel channel ID
Returns:
sampling interval
References SONChannelInfo::getDivide(), SONChannelInfo::getLChanDvd(), SONFileHeader::getSystemID(), and SONFileHeader::getTimePerADC().
Referenced by getSamplingFrequency(), SONADCMarkChannel::read(), and SONADCChannels::read().
uint32_t SONFile::getNBlocks (uint16_t channel) const [inline, virtual]
Get number of blocks for a given channel
Parameters:
channel channel ID
Returns:
number of blocks
References SONChannelInfo::getNBlocks().
Referenced by SONEventChannel::read(), SONBlockHeaders::read(), SONADCMarkChannel::read(), SONADCChannels::read(), and SONBlockHeaders::readNext().
uint16_t SONFile::getNSamplesInBlock (uint16_t channel, uint32_t block) const [inline, virtual]
Get number of samples in a given block for a given channel
Parameters:
channel channel ID
block block number
Returns:
number of samples actually recorded
References SONBlockHeaders::getNSamplesInBlock().
Referenced by SONEventChannel::read(), SONADCMarkChannel::read(), and SONADCChannels::read().
int64_t SONFile::getNSamples (uint16_t channel) const [inline, virtual]
Get number of samples for a given channel
Parameters:
channel channel ID
Returns:
total number of samples
References SONBlockHeaders::getNSamples().
Referenced by SONEventChannel::read(), SONADCMarkChannel::read(), and SONADCChannels::read().
uint16_t SONFile::getNSamplesPerWaveform (uint16_t channel) const [inline, virtual]
Get number of samples per waveform for a given channel
Parameters:
channel channel ID
Returns:
number of samples per waveform
References SONChannelInfo::getNSamplesPerWaveform().
Referenced by SONADCMarkChannel::read().
int64_t SONFile::getFirstBlockOffset (uint16_t channel) const [inline, virtual]
Get file offset of first block of data for a given channel
Parameters:
channel channel ID
Returns:
offset
References SONChannelInfo::getFirstBlockOffset().
Referenced by SONBlockHeaders::readNext().
int64_t SONFile::getBlockOffset (uint16_t channel, uint32_t block) const [inline, virtual]
Get file offset of a given block of data for a given channel
Parameters:
channel channel ID
block block number
Returns:
offset
References SONBlockHeaders::getBlockOffset().
Referenced by SONEventChannel::read(), SONADCMarkChannel::read(), and SONADCChannels::read().
bool SONFile::isADCChannel (uint16_t channel) const [inline, virtual]
Test if a given channel contains ADC data
Parameters:
channel channel ID
Returns:
test result
References SONChannelInfo::isADCChannel().
Referenced by SONExtractor::extract(), and SONADCChannels::read().
bool SONFile::isADCMarkChannel (uint16_t channel) const [inline, virtual]
Test if a given channel contains ADC Mark data
Parameters:
channel channel ID
Returns:
test result
References SONChannelInfo::isADCMarkChannel().
Referenced by SONExtractor::extract(), and SONADCMarkChannel::read().
bool SONFile::isEventChannel (uint16_t channel) const [inline, virtual]
Test if a given channel contains Event data
Parameters:
channel channel ID
Returns:
test result
References SONChannelInfo::isEventChannel().
Referenced by SONExtractor::extract(), and SONEventChannel::read().
bool SONFile::isSimpleEventChannel (uint16_t channel) const [inline, virtual]
Test if a given channel contains simple Event data
Parameters:
channel channel ID
Returns:
test result
References SONChannelInfo::isSimpleEventChannel().
Referenced by SONEventChannel::read(), and SONEventChannel::write().
bool SONFile::isMarkerChannel (uint16_t channel) const [inline, virtual]
Test if a given channel contains Marker data
Parameters:
channel channel ID
Returns:
test result
References SONChannelInfo::isMarkerChannel().
bool SONFile::isTextMarkChannel (uint16_t channel) const [inline, virtual]
Test if a given channel contains Text Marker data
Parameters:
channel channel ID
Returns:
test result
References SONChannelInfo::isTextMarkChannel().
The documentation for this class was generated from the following files:
sonfile.h
sonfile.cpp