process_smrconvert: SONEventChannel Class Reference
SONEventChannel Class Reference
#include <soneventchannel.h>
Public Member Functions
SONEventChannel (SONFile *file, uint16_t channel)
virtual ~SONEventChannel ()
virtual void read () throw (SONError)
virtual void write (ostream &out) const throw (SONError)
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
SONEventChannel::SONEventChannel (SONFile * file, uint16_t channel)
Constructor
Parameters:
file input file
channel channel ID
SONEventChannel::~SONEventChannel () [virtual]
Destructor
Member Function Documentation
void SONEventChannel::read () throw (SONError) [virtual]
Read Event data
References SONChannel::blockHeaderSize, SONChannel::channel, SONChannel::file, SONFile::getBlockOffset(), SONFile::getNBlocks(), SONFile::getNSamples(), SONFile::getNSamplesInBlock(), SONFile::isEventChannel(), SONFile::isSimpleEventChannel(), SONChannel::markerSize, and SONFile::readBlockHeaders().
Referenced by SONExtractor::extractEvt().
void SONEventChannel::write (ostream & out) const throw (SONError) [virtual]
Write event data
Parameters:
out output stream (.evt file)
References SONChannel::channel, SONChannel::file, SONFile::getSecondsPerTick(), and SONFile::isSimpleEventChannel().
Referenced by SONExtractor::extractEvt().
The documentation for this class was generated from the following files:
soneventchannel.h
soneventchannel.cpp