process_smrconvert: SONADCMarkChannel Class Reference
SONADCMarkChannel Class Reference
#include <sonadcmarkchannel.h>
Public Member Functions
SONADCMarkChannel (SONFile *file, uint16_t channel)
virtual ~SONADCMarkChannel ()
virtual void read () throw (SONError)
virtual void write (ostream &times, ostream &waveforms, bool reverse=false) const throw (SONError)
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
SONADCMarkChannel::SONADCMarkChannel (SONFile * file, uint16_t channel)
Constructor
Parameters:
file input file
channel channel ID
SONADCMarkChannel::~SONADCMarkChannel () [virtual]
Destructor
Member Function Documentation
void SONADCMarkChannel::read () throw (SONError) [virtual]
Read ADC data
References SONChannel::blockHeaderSize, SONChannel::file, SONFile::getBlockOffset(), SONFile::getNBlocks(), SONFile::getNSamples(), SONFile::getNSamplesInBlock(), SONFile::getNSamplesPerWaveform(), SONFile::getTicksPerSI(), SONFile::isADCMarkChannel(), SONChannel::markerSize, and SONFile::readBlockHeaders().
Referenced by SONExtractor::extractSpk().
void SONADCMarkChannel::write (ostream & times, ostream & waveforms, bool reverse = false) const throw (SONError) [virtual]
Write ADC data
Parameters:
times timestamp file
waveforms waveform file
reverse reverse values?
Referenced by SONExtractor::extractSpk().
The documentation for this class was generated from the following files:
sonadcmarkchannel.h
sonadcmarkchannel.cpp