set(scripts
	cnt
	duration
	ndm_clean
	ndm_concatenate
	ndm_extractchannels
	ndm_extractleds
	ndm_extractspikes
	ndm_functions
	ndm_hipass
	ndm_lfp
	ndm_mergedat
	ndm_ncs2dat
	ndm_nev2evt
	ndm_nvt2spots
	ndm_pca
	ndm_recolorchannels
	ndm_reorderchannels
	ndm_resample
	ndm_smi2sts
	ndm_smr2dat
	ndm_smr2evt
	ndm_start
	ndm_transcodevideo
	ndm_tsp2sts
	pad
	process_renameevents_SPWR
	process_renameevents_TMaze
	process_reorderclusters
	rn)
install(PROGRAMS ${scripts} DESTINATION ${CMAKE_INSTALL_BINDIR})

ndm_add_manpages(scripts
    cnt.docbook
    duration.docbook
    ndm.docbook
    ndm_recolorchannels.docbook
    ndm_start.docbook
    pad.docbook
    process_reorderclusters.docbook
    rn.docbook
)
