#!/bin/bash

#////////////////////////////////////////////////////////////////////////////
#//
#//   Count files
#//
#//   copyright       (C) 2010 by Michaël Zugaro
#//   email           michael.zugaro@college-de-france.fr
#//
#//   This program is free software; you can redistribute it and/or modify
#//   it under the terms of the GNU General Public License as published by
#//   the Free Software Foundation; either version 3 of the License, or
#//   (at your option) any later version.
#//
#////////////////////////////////////////////////////////////////////////////

# Source helper functions
source ndm_functions

program=$(basename $0)
while true
do
	case $1 in
		-h|--help)
			echo "usage: $program [file1 file2...]"
			echo " count unique existing files (or directories) among listed names"
			exit $NO_ERROR
			;;
		*)
			break
			;;
	esac
done

if [ $# -eq 0 ]
then
	ls [0-9]* 2>/dev/null | wc -l
else
	ls $* 2>/dev/null|sort|uniq|wc -l
# 	echo $#
fi

