process_smrconvert: SONADCChannels Class Reference
SONADCChannels Class Reference
#include <sonadcchannels.h>
Public Member Functions
SONADCChannels (SONFile *file, uint16_t nChannels, uint16_t *channels, int32_t nBufferSamples=8192)
virtual ~SONADCChannels ()
virtual void reset ()
virtual bool done () const
virtual void read () throw (SONError)
virtual void write (ostream &out, bool reverse=false) const throw (SONError)
virtual float percentDone () const
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
SONADCChannels::SONADCChannels (SONFile * file, uint16_t nChannels, uint16_t * channels, int32_t nBufferSamples = 8192)
Constructor
Parameters:
file input file
nChannels number of channels to process
channels list of channel IDs
nBufferSamples read/write block size (in samples per channel)
SONADCChannels::~SONADCChannels () [virtual]
Destructor
Member Function Documentation
void SONADCChannels::reset () [inline, virtual]
Restart from sample 0
bool SONADCChannels::done () const [virtual]
Test if the SON file contains more data for the selected channels
Returns:
true if there is no data left
Referenced by SONExtractor::extractDat(), and write().
void SONADCChannels::read () throw (SONError) [virtual]
Read ADC data (one buffer at a time)
References SONFile::getBlockOffset(), SONFile::getNBlocks(), SONFile::getNSamples(), SONFile::getNSamplesInBlock(), SONFile::getTicksPerSI(), SONFile::isADCChannel(), and SONFile::readBlockHeaders().
Referenced by SONExtractor::extractDat().
void SONADCChannels::write (ostream & out, bool reverse = false) const throw (SONError) [virtual]
Write ADC data (one buffer at a time)
Parameters:
out output stream (.dat file)
reverse should data values be reversed?
References done().
Referenced by SONExtractor::extractDat().
float SONADCChannels::percentDone () const [inline, virtual]
Return percentage of input file read
Referenced by SONExtractor::extractDat().
The documentation for this class was generated from the following files:
sonadcchannels.h
sonadcchannels.cpp