process_smrconvert: SONFileHeader Class Reference
SONFileHeader Class Reference
#include <sonfileheader.h>
Public Member Functions
SONFileHeader (SONFile *file)
virtual ~SONFileHeader ()
virtual void read ()
virtual int16_t getNChannels () const
virtual int16_t getSystemID () const
virtual double getSecondsPerTick () const
virtual uint16_t getTimePerADC () const
Friends
class SONExtractor
ostream & operator<< (ostream &out, const SONFileHeader &fileHeader)
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
SONFileHeader::SONFileHeader (SONFile * file)
Constructor
Parameters:
file input file stream
SONFileHeader::~SONFileHeader () [virtual]
Destructor
Member Function Documentation
void SONFileHeader::read () [virtual]
Read SON file header
Referenced by SONFile::init().
int16_t SONFileHeader::getNChannels () const [inline, virtual]
Get number of channels in SON file
Returns:
number of channels
Referenced by SONFile::getNChannels(), and SONFile::init().
int16_t SONFileHeader::getSystemID () const [inline, virtual]
Get system ID (Spike 2 version)
Returns:
system ID
Referenced by SONFile::getTicksPerSI(), and SONFile::getVersion().
double SONFileHeader::getSecondsPerTick () const [inline, virtual]
Conversion from ticks to seconds
Returns:
clock tick duration (in s)
Referenced by SONFile::getSecondsPerTick().
uint16_t SONFileHeader::getTimePerADC () const [inline, virtual]
Get time units per ADC interrupt
Returns:
time per ADC
Referenced by SONFile::getTicksPerSI().
The documentation for this class was generated from the following files:
sonfileheader.h
sonfileheader.cpp