process_smrconvert: SONBlockHeaders Class Reference
SONBlockHeaders Class Reference
#include <sonblockheaders.h>
Public Member Functions
SONBlockHeaders ()
SONBlockHeaders (SONFile *file, uint16_t channel)
virtual void init (SONFile *file, uint16_t channel)
virtual ~SONBlockHeaders ()
virtual void read () throw (SONError)
virtual void readNext () throw (SONError)
virtual int64_t getNSamples () const
virtual uint32_t getNBlocks () const
virtual int64_t getBlockOffset (uint32_t block) const
virtual uint16_t getNSamplesInBlock (uint16_t i) const
Static Public Attributes
static const int diskBlock = 512
Friends
class SONExtractor
Detailed Description
Author:
Michael Zugaro
Constructor & Destructor Documentation
SONBlockHeaders::SONBlockHeaders ()
Default constructor (necessary to create arrays of SONBlockHeaders)
See also:
init
SONBlockHeaders::SONBlockHeaders (SONFile * file, uint16_t channel)
Constructor
Parameters:
file input file
channel channel number
SONBlockHeaders::~SONBlockHeaders () [virtual]
Destructor
Member Function Documentation
void SONBlockHeaders::init (SONFile * file, uint16_t channel) [inline, virtual]
Initialization (necessary to create arrays of SONBlockHeaders)
Parameters:
file input file
channel channel number
void SONBlockHeaders::read () throw (SONError) [virtual]
Read all block headers
References SONFile::getNBlocks(), and readNext().
Referenced by SONFile::readBlockHeaders().
void SONBlockHeaders::readNext () throw (SONError) [virtual]
Read next channel block header
References diskBlock, SONFile::getFirstBlockOffset(), SONFile::getNBlocks(), and SONFile::getVersion().
Referenced by read().
int64_t SONBlockHeaders::getNSamples () const [inline, virtual]
Get total number of samples
Referenced by SONFile::getNSamples().
uint32_t SONBlockHeaders::getNBlocks () const [inline, virtual]
Get number of blocks
Returns:
number of blocks
int64_t SONBlockHeaders::getBlockOffset (uint32_t block) const [inline, virtual]
Get block pointer
Parameters:
block block number
Returns:
block offset in file
Referenced by SONFile::getBlockOffset().
uint16_t SONBlockHeaders::getNSamplesInBlock (uint16_t i) const [inline, virtual]
Get number of block samples
Parameters:
i block number
Returns:
number of samples in block
Referenced by SONFile::getNSamplesInBlock().
Member Data Documentation
const int SONBlockHeaders::diskBlock = 512 [static]
file offset coeff (file format version >= 9)
Referenced by readNext().
The documentation for this class was generated from the following files:
sonblockheaders.h
sonblockheaders.cpp